CC = gcc
CFLAGS = -Wall -std=c17

all: zajecia
zajecia:
	gcc -Wall -c zajecia.c
	gcc -Wall -o main zajecia.o

zaj1:
	gcc -Wall -c zaj1.c
	gcc -Wall -o main zaj1.c
clean:
	rm -f main zajecia.o zaj1.o

